apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bankapplications.bank.example.com
spec:
  group: bank.example.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              appName:
                type: string
              version:
                type: string
              replicas:
                type: integer
                minimum: 1
                maximum: 10
              database:
                type: object
                properties:
                  enabled:
                    type: boolean
                  type:
                    type: string
                    enum: [mysql, postgresql]
  scope: Namespaced
  names:
    plural: bankapplications
    singular: bankapplication
    kind: BankApplication
    shortNames:
    - bapp
