apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: bank-app
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
