apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nginx-pvc
  namespace: bank-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: nginx
