apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-cleanup
  namespace: bank-app
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes for testing
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "🕒 Running scheduled cleanup at $(date)"
                echo "🧹 Cleaning up temporary files..."
                echo "✅ Cleanup completed successfully"
            resources:
              requests:
                memory: "32Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "50m"
          restartPolicy: OnFailure
